version: '3'
services:
  attacker:
    image: "udzura/bigbridge-attacker:latest"
  defender:
    image: "udzura/bigbridge-defender:latest"
    ports:
     - "127.0.0.1:12222:22"
     - "127.0.0.1:18080:80"
    env_file: .env
    environment:
    - GITHUB_TOKEN
